apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: 2048-game
spec:
  selector:
    app: 2048-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP