apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps                
  namespace: argocd 

spec:
  project: default            
  source:
    repoURL: https://github.com/olaolatunbos/AKS-Production-Grade-Deployment.git  
    targetRevision: HEAD      
    path: k8s-specifications

  destination:
    server: https://kubernetes.default.svc  
    namespace: apps  
                 
  syncPolicy:
    automated:
      prune: true        
      selfHeal: true        
    syncOptions:
      - CreateNamespace=true  
