name: Build and Deploy Flask App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/2048:latest -f 2048-game/Dockerfile .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/2048:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/2048:latest
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppName: 2048-game
